### ISSUE TITLE
Unable to start dev server

### ISSUE THREAD

**Issue by Septias** [webxdc/webxdc-dev#26]
I would like to help developing webxdc-dev but I'm unable to even start the basic project:

![image](https://user-images.githubusercontent.com/39526136/185619214-cdc53a16-68ae-438b-82a0-04de3dc93779.png)

Steps to reproduce:
- pnpm install
- pnpm run dev -- run /home/sebastian/coding/hello/hello.xdc

I'm running node v. 18.7 which might cause problems?

**Comment by faassen** [comment]
Have you tried with `npm`? I don't think there's a pnmp lock file so it won't install the right versions. I don't think we should use multiple installation tools to develop this project and everything has been developed with `npm`.

**Comment by Septias** [comment]
I also tried using npm which did not work. 
I can give it another try later

**Comment by faassen** [comment]
Okay, npm not working is definitely an issue! I tried to reproduce it by removing `node_modules`, doing a new `npm install` but it's working for me so I'm curious to see what's the difference. I'm on npm `8.11.0`.
