### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by WofWca** [webxdc/webxdc-dev#38]
There are some long-unreleased changes. Looks like we can release them by simply pushing a tag.

I have the permission to do this, but I want someone's approval.

**Comment by r10s** [comment]
what does a release tag mean in practise for webxdc-dev?

if it is not much more than a formal thing, i'd say, go for it :) there are lots of improvements that are worth rewarded by a release (i personally do not used webxdc-dev currently, so i cannot judge the overall state)

**Comment by WofWca** [comment]
> what does a release tag mean in practise for webxdc-dev?

When you push a tag, it publishes it to https://www.npmjs.com/

**Comment by r10s** [comment]
i see. recent changes in README and updated dependencies - and older changes are tested meanwhile by you - so, i'd say go for a new release :)

**Comment by WofWca** [comment]
I forgot to mention the changelog and `package.json`. After #39 it's really a matter of pushing a tag.
