### ISSUE TITLE
No screenshot on npmjs.com

### ISSUE THREAD

**Issue by WofWca** [webxdc/webxdc-dev#40]
![image](https://user-images.githubusercontent.com/39462442/220581876-c8b60660-a835-4ab5-ac0a-dcc41688c6e5.png)

Idk if it's something that needs fixing. Maybe it's not worth packaging effectively useless stuff inside the npm package to save space.

**Comment by r10s** [comment]
ftr, this is the url: https://www.npmjs.com/package/webxdc-dev

i do not know, how these sites are used in practise, but, as a first impression, to me it does not look good, i would fix that.

as a pragmatic approach, we could probably just replace `./screenshot.png` in the README by `https://raw.githubusercontent.com/webxdc/webxdc-dev/main/screenshot.png`
