### ISSUE TITLE
do a new release including the new import/export API

### ISSUE THREAD

**Issue by adbenitez** [webxdc/webxdc-dev#42]

**Comment by faassen** [comment]
I automated how to do releases; it's documented in the README and should be easy. If you need to change something about npm do let me know!

**Comment by adbenitez** [comment]
great! thanks a lot!

**Comment by adbenitez** [comment]
closed by https://github.com/webxdc/webxdc-dev/commit/db00ae2585a9131415bdc1603fe76da7be1a5e17
